### ISSUE TITLE
Move redirect auth credentials to site config 

### ISSUE THREAD

**Issue by kahummer** [onaio/gisida#407] opened 2020-01-30 08:43 UTC
Any time we change the redirect URL we have to re-build our bundle. would be cool to have this on the configs file.

- [x] Irfsomalia

**Comment by kelvin-muchiri** [comment] 2020-02-03 14:59
Duplicate of: https://github.com/onaio/gisida-react/issues/161

**Closed** 2020-02-03 14:59 UTC
